/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    Backgammon: {
      address: "0x49b8e3b089d4ebf9f37b1da9b839ec013c2cd8c9",
      abi: [
        {
          type: "constructor",
          inputs: [],
          stateMutability: "payable",
        },
        {
          type: "receive",
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "_moveWhite",
          inputs: [
            {
              name: "_from",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_to",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "black",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "blackAvailableMoves",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "blackDiceRolled",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "blackMovesCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "blackPlayer",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "blackStartDice",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "blackStartDiceRolled",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "depositStake",
          inputs: [],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "fundsWithdrawn",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "gameActive",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "gameStarted",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getBalance",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getGameInfo",
          inputs: [],
          outputs: [
            {
              name: "_whitePlayer",
              type: "address",
              internalType: "address",
            },
            {
              name: "_blackPlayer",
              type: "address",
              internalType: "address",
            },
            {
              name: "_stakeAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_gameStarted",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "_gameActive",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "_winner",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "_fundsWithdrawn",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "_balance",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_whiteStartDice",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_blackStartDice",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_whiteStartDiceRolled",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "_blackStartDiceRolled",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "hasBlackPossibleMove",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "hasWhitePossibleMove",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "isItBlackTurn",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "joinGame",
          inputs: [],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "moveBlack",
          inputs: [
            {
              name: "_from",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_to",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "moveWhite",
          inputs: [
            {
              name: "_from",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_to",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "rollDiceBlack",
          inputs: [],
          outputs: [
            {
              name: "dice1",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "dice2",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "rollDiceWhite",
          inputs: [],
          outputs: [
            {
              name: "dice1",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "dice2",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "rollStartDiceBlack",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "rollStartDiceWhite",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "stakeAmount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "white",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "whiteAvailableMoves",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "whiteDiceRolled",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "whiteMovesCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "whitePlayer",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "whiteStartDice",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "whiteStartDiceRolled",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "winner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "withdraw",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "BlackTurn",
          inputs: [
            {
              name: "_from",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "_to",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "DiceRolled",
          inputs: [
            {
              name: "isBlack",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
            {
              name: "dice1",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "dice2",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "FirstTurnDetermined",
          inputs: [
            {
              name: "isBlackTurn",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
            {
              name: "dice1",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "dice2",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "FundsWithdrawn",
          inputs: [
            {
              name: "winner",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "GameStarted",
          inputs: [
            {
              name: "whitePlayer",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "blackPlayer",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "stakeAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "GameWon",
          inputs: [
            {
              name: "winner",
              type: "uint8",
              indexed: false,
              internalType: "uint8",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "StakeDeposited",
          inputs: [
            {
              name: "player",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "StartDiceRolled",
          inputs: [
            {
              name: "player",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "dice",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "TurnSwitched",
          inputs: [
            {
              name: "isBlackTurn",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "WhiteTurn",
          inputs: [
            {
              name: "_from",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "_to",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 134,
    },
  },
  84532: {
    Backgammon: {
      address: "0x85d905310f2b695970307cdfadd15e4c44faf052",
      abi: [
        {
          type: "constructor",
          inputs: [],
          stateMutability: "payable",
        },
        {
          type: "receive",
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "_moveWhite",
          inputs: [
            {
              name: "_from",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_to",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "black",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "blackAvailableMoves",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "blackDiceRolled",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "blackMovesCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "blackPlayer",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "blackStartDice",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "blackStartDiceRolled",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "depositStake",
          inputs: [],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "fundsWithdrawn",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "gameActive",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "gameStarted",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getBalance",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getGameInfo",
          inputs: [],
          outputs: [
            {
              name: "_whitePlayer",
              type: "address",
              internalType: "address",
            },
            {
              name: "_blackPlayer",
              type: "address",
              internalType: "address",
            },
            {
              name: "_stakeAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_gameStarted",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "_gameActive",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "_winner",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "_fundsWithdrawn",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "_balance",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_whiteStartDice",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_blackStartDice",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_whiteStartDiceRolled",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "_blackStartDiceRolled",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "hasBlackPossibleMove",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "hasWhitePossibleMove",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "isItBlackTurn",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "joinGame",
          inputs: [],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "moveBlack",
          inputs: [
            {
              name: "_from",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_to",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "moveWhite",
          inputs: [
            {
              name: "_from",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_to",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "rollDiceBlack",
          inputs: [],
          outputs: [
            {
              name: "dice1",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "dice2",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "rollDiceWhite",
          inputs: [],
          outputs: [
            {
              name: "dice1",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "dice2",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "rollStartDiceBlack",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "rollStartDiceWhite",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "stakeAmount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "white",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "whiteAvailableMoves",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "whiteDiceRolled",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "whiteMovesCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "whitePlayer",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "whiteStartDice",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "whiteStartDiceRolled",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "winner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "withdraw",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "BlackTurn",
          inputs: [
            {
              name: "_from",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "_to",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "DiceRolled",
          inputs: [
            {
              name: "isBlack",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
            {
              name: "dice1",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "dice2",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "FirstTurnDetermined",
          inputs: [
            {
              name: "isBlackTurn",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
            {
              name: "dice1",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "dice2",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "FundsWithdrawn",
          inputs: [
            {
              name: "winner",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "GameStarted",
          inputs: [
            {
              name: "whitePlayer",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "blackPlayer",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "stakeAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "GameWon",
          inputs: [
            {
              name: "winner",
              type: "uint8",
              indexed: false,
              internalType: "uint8",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "StakeDeposited",
          inputs: [
            {
              name: "player",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "StartDiceRolled",
          inputs: [
            {
              name: "player",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "dice",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "TurnSwitched",
          inputs: [
            {
              name: "isBlackTurn",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "WhiteTurn",
          inputs: [
            {
              name: "_from",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "_to",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 34456462,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
